import Head from 'next/head'
import { Layout } from 'antd';
import type { PropsWithChildren } from 'react'
const { Header, Footer, Sider, Content } = Layout;
const Home = ({children}:PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout className='app-container'>
        <Header className='app-header'>
          this is header
        </Header>
        <Content className='app-main'>{children}</Content>
        <Footer className='app-footer'>
          this is footer
        </Footer>
      </Layout>
    </>
    
  )
}

export default Home
